.TH "Audio.LoadAudioSettings" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audio.LoadAudioSettings \- This script is used to load the audio settings from the player prefs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
This script is used to load the audio settings from the player prefs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
