.TH "Audio" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audio
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioSourcePool\fP"
.br
.RI "A pool of AudioSources that can be used to play audio clips at a specific position\&. "
.ti -1c
.RI "class \fBLoadAudioSettings\fP"
.br
.RI "This script is used to load the audio settings from the player prefs\&. "
.ti -1c
.RI "class \fBPlayMusicQueue\fP"
.br
.RI "This script is used to play a queue of songs\&. "
.ti -1c
.RI "class \fBVolumeController\fP"
.br
.RI "This script is used to control the volume of an audio mixer parameter\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
