.TH "Audio.VolumeController" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audio.VolumeController \- This script is used to control the volume of an audio mixer parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMenu\&.SettingEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBSave\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "abstract void \fBSave\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This script is used to control the volume of an audio mixer parameter\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void Audio\&.VolumeController\&.Save ()\fC [virtual]\fP"

.PP
Implements \fBMenu\&.SettingEntry\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
