.TH "Audio.PlayMusicQueue" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audio.PlayMusicQueue \- This script is used to play a queue of songs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
This script is used to play a queue of songs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
