.TH "Bomb.Explosion" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bomb.Explosion
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetupExplosionBoundingBox\fP (float distance, Vector3 direction)"
.br
.ti -1c
.RI "void \fBDestroyAfter\fP (float time)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
