.TH "Bomb.BombData" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bomb.BombData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBombData\fP (int power)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpower\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBExplosionDuration\fP = 0\&.8f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
