.TH "Bonus" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bonus
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseBonus\fP"
.br
.ti -1c
.RI "class \fBDecreaseBombAmountBonus\fP"
.br
.ti -1c
.RI "class \fBDecreaseBombPowerBonus\fP"
.br
.ti -1c
.RI "class \fBDecreaseSpeedBonus\fP"
.br
.ti -1c
.RI "class \fBIncreaseBombAmountBonus\fP"
.br
.ti -1c
.RI "class \fBIncreaseBombPowerBonus\fP"
.br
.ti -1c
.RI "class \fBIncreaseSpeedBonus\fP"
.br
.ti -1c
.RI "class \fBPushBombBonus\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
