.TH "Bonus.DecreaseBombPowerBonus" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bonus.DecreaseBombPowerBonus
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBonus\&.BaseBonus\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPlayerTakeBonus\fP (GameObject player)"
.br
.in -1c

Protected Member Functions inherited from \fBBonus\&.BaseBonus\fP
.in +1c
.ti -1c
.RI "abstract void \fBOnPlayerTakeBonus\fP (GameObject player)"
.br
.ti -1c
.RI "virtual void \fBPlaySound\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void Bonus\&.DecreaseBombPowerBonus\&.OnPlayerTakeBonus (GameObject player)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBBonus\&.BaseBonus\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
