.TH "Core.EntityHealth" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core.EntityHealth
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBHealthAction\fP (GameObject go)"
.br
.ti -1c
.RI "void \fBPerformDamage\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "HealthAction \fBOnDeath\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
