.TH "Core" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDontDestroyThisGameObjectOnLoad\fP"
.br
.ti -1c
.RI "class \fBEntityHealth\fP"
.br
.ti -1c
.RI "class \fBInfiniteRotation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
