.TH "Game" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGameBonus\fP"
.br
.ti -1c
.RI "class \fBGameBonuses\fP"
.br
.ti -1c
.RI "struct \fBGameEndedEvent\fP"
.br
.ti -1c
.RI "class \fBGameStateManager\fP"
.br
.ti -1c
.RI "class \fBPlayerManager\fP"
.br
.ti -1c
.RI "class \fBReadyCountdown\fP"
.br
.RI "A countdown that is displayed before the game starts\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGameState\fP { \fBInitialization\fP, \fBTerrainGenerated\fP, \fBReady\fP, \fBPlaying\fP, \fBPaused\fP, \fBResumed\fP, \fBEnded\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
