.TH "IA" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IA
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRaycastResult\fP"
.br
.ti -1c
.RI "class \fBTerrainStateManager\fP"
.br
.ti -1c
.RI "struct \fBTouchData\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTerrainTileState\fP { \fBNone\fP, \fBBomb\fP, \fBIndestructibleWall\fP, \fBWall\fP }"
.br
.ti -1c
.RI "enum \fBMovementDirection\fP { \fBNorth\fP, \fBWest\fP, \fBSouth\fP, \fBEast\fP, \fBNone\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
