.TH "IA.TouchData" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IA.TouchData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBPosition\fP"
.br
.ti -1c
.RI "bool \fBIsBomb\fP"
.br
.ti -1c
.RI "bool \fBIsWall\fP"
.br
.ti -1c
.RI "bool \fBIsTerrain\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
