.TH "IA.TerrainStateManager" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IA.TerrainStateManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBSetTileState\fP (int x, int y, TerrainTileState state)"
.br
.ti -1c
.RI "void \fBRemoveTile\fP (int x, int y)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTerrainStateManager\fP \fBGetInstance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBWidth\fP = 17"
.br
.ti -1c
.RI "const int \fBHeight\fP = 11"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
