.TH "Lobby.LobbyController" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lobby.LobbyController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBPlayerInputs\&.IPlayerHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandlePlayerJoined\fP (PlayerInput playerInput)"
.br
.ti -1c
.RI "void \fBHandlePlayerLeft\fP (PlayerInput playerInput)"
.br
.ti -1c
.RI "void \fBOnPlayerRemoveHandler\fP (int playerIndex)"
.br
.ti -1c
.RI "void \fBReturnToMainMenu\fP ()"
.br
.ti -1c
.RI "void \fBOnSelectLeftCharacterHandler\fP (int playerIndex)"
.br
.ti -1c
.RI "void \fBOnSelectRightCharacterHandler\fP (int playerIndex)"
.br
.in -1c
.in +1c
.ti -1c
.RI "void \fBHandlePlayerJoined\fP (PlayerInput playerInput)"
.br
.ti -1c
.RI "void \fBHandlePlayerLeft\fP (PlayerInput playerInput)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBLobbyController\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Lobby\&.LobbyController\&.HandlePlayerJoined (PlayerInput playerInput)"

.PP
Implements \fBPlayerInputs\&.IPlayerHandler\fP\&.
.SS "void Lobby\&.LobbyController\&.HandlePlayerLeft (PlayerInput playerInput)"

.PP
Implements \fBPlayerInputs\&.IPlayerHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
