.TH "Lobby.LobbyPlayerSlotUI" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lobby.LobbyPlayerSlotUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateUI\fP (\fBPlayerState\fP playerState)"
.br
.ti -1c
.RI "void \fBEnableSlotUI\fP (int playerIndex)"
.br
.ti -1c
.RI "void \fBDisableSlotUI\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsDisable\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< int > \fBOnNextButtonClicked\fP"
.br
.ti -1c
.RI "Action< int > \fBOnPreviousButtonClicked\fP"
.br
.ti -1c
.RI "Action< int > \fBOnRemoveButtonClicked\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
