.TH "Lobby.LobbyUI" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lobby.LobbyUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowStartGameText\fP ()"
.br
.ti -1c
.RI "void \fBHideStartGameText\fP ()"
.br
.ti -1c
.RI "void \fBEnableSlotUI\fP (int playerIndex)"
.br
.ti -1c
.RI "void \fBDisableSlotUI\fP (int playerIndex)"
.br
.ti -1c
.RI "void \fBUpdateSlotUI\fP (\fBPlayerState\fP playerState)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
