.TH "Menu.SettingEntry" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.SettingEntry \- SettingEntry is used to easily save the settings\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBAudio\&.VolumeController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBSave\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
SettingEntry is used to easily save the settings\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
