.TH "Menu" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEndGameMenu\fP"
.br
.RI "EndGameMenu is used to display the end game menu\&. "
.ti -1c
.RI "class \fBMenuFunctionUtils\fP"
.br
.RI "\fBMenu\fP Function \fBUtils\fP is used to store functions that are used in the menu\&. "
.ti -1c
.RI "class \fBSettingEntry\fP"
.br
.RI "SettingEntry is used to easily save the settings\&. "
.ti -1c
.RI "class \fBUISettingsManager\fP"
.br
.RI "UISettingsManager is used to manage the settings menu\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
