.TH "Menu.EndGameMenu" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.EndGameMenu \- EndGameMenu is used to display the end game menu\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnRestartButtonClicked\fP ()"
.br
.RI "On restart button clicked\&. "
.ti -1c
.RI "void \fBOnQuitButtonClicked\fP ()"
.br
.RI "On quit button clicked\&. "
.in -1c
.SH "Detailed Description"
.PP 
EndGameMenu is used to display the end game menu\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
