.TH "Menu.UISettingsManager" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.UISettingsManager \- UISettingsManager is used to manage the settings menu\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSaveSettings\fP ()"
.br
.ti -1c
.RI "void \fBOpenSettings\fP ()"
.br
.ti -1c
.RI "void \fBReturnToPreviousMenu\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
UISettingsManager is used to manage the settings menu\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
