.TH "Player.PlayerMovement" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.PlayerMovement \- PlayerHandler is used to handle the input of a player\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBPlayerInputHandler\fP playerInputHandler)"
.br
.RI "Initialize the player handler\&. "
.ti -1c
.RI "void \fBAddSpeedBonus\fP ()"
.br
.RI "Add a speed bonus\&. "
.ti -1c
.RI "void \fBRemoveSpeedBonus\fP ()"
.br
.RI "Remove a speed bonus\&. "
.ti -1c
.RI "void \fBUpdateInputVector\fP (Vector2 inputVector)"
.br
.RI "Update the input vector\&. "
.ti -1c
.RI "void \fBFixedUpdate\fP ()"
.br
.RI "FixedUpdate is called every fixed framerate frame, if the MonoBehaviour is enabled\&. "
.in -1c
.SH "Detailed Description"
.PP 
PlayerHandler is used to handle the input of a player\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Player\&.PlayerMovement\&.Initialize (\fBPlayerInputHandler\fP playerInputHandler)"

.PP
Initialize the player handler\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerInputHandler\fP 
.RE
.PP

.SS "void Player\&.PlayerMovement\&.UpdateInputVector (Vector2 inputVector)"

.PP
Update the input vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIinputVector\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
