.TH "Player" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCursorModelAnimation\fP"
.br
.RI "CursorModelAnimation is used to animate the cursor model\&. "
.ti -1c
.RI "class \fBPlayerBombController\fP"
.br
.RI "PlayerController is used to control the bombs of the player\&. "
.ti -1c
.RI "class \fBPlayerEffects\fP"
.br
.RI "PlayerEffects is used to store the effects of the player\&. "
.ti -1c
.RI "class \fBPlayerGameObjectRegistry\fP"
.br
.RI "PlayerGameObjectRegistry is used to get the player prefab\&. "
.ti -1c
.RI "class \fBPlayerModelAnimation\fP"
.br
.RI "PlayerModelAnimation is used to animate the player model\&. "
.ti -1c
.RI "class \fBPlayerMovement\fP"
.br
.RI "PlayerHandler is used to handle the input of a player\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPlayerOrientation\fP { \fBTop\fP, \fBRight\fP, \fBBottom\fP, \fBLeft\fP }"
.br
.RI "PlayerHandler is used to handle the input of a player\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
