.TH "PlayerInputs.IPlayerHandler" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerInputs.IPlayerHandler \- IPlayerHandler is used to handle the input of a player\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLobby\&.LobbyController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandlePlayerJoined\fP (PlayerInput playerInput)"
.br
.ti -1c
.RI "void \fBHandlePlayerLeft\fP (PlayerInput playerInput)"
.br
.in -1c
.SH "Detailed Description"
.PP 
IPlayerHandler is used to handle the input of a player\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
