.TH "PlayerInputs" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerInputs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGamePlayerInputManager\fP"
.br
.RI "GamePlayerInputManager is used to handle the input of the players\&. "
.ti -1c
.RI "interface \fBIPlayerHandler\fP"
.br
.RI "IPlayerHandler is used to handle the input of a player\&. "
.ti -1c
.RI "class \fBPlayerInputHandler\fP"
.br
.RI "PlayerInputHandler is used to handle the input of a player\&. "
.ti -1c
.RI "class \fBPlayerInputRegistry\fP"
.br
.RI "PlayerInputRegistry is used to keep track of all the \fBPlayerInputs\fP in the scene\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
