.TH "Player.PlayerGameObjectRegistry" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.PlayerGameObjectRegistry \- PlayerGameObjectRegistry is used to get the player prefab\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GameObject \fBGetOneWithIndex\fP (int index)"
.br
.RI "Get the player prefab with the given index\&. "
.in -1c
.SH "Detailed Description"
.PP 
PlayerGameObjectRegistry is used to get the player prefab\&. 
.SH "Member Function Documentation"
.PP 
.SS "GameObject Player\&.PlayerGameObjectRegistry\&.GetOneWithIndex (int index)"

.PP
Get the player prefab with the given index\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The index of the player prefab 
.RE
.PP
\fBReturns\fP
.RS 4
The player prefab 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
