.TH "Player.CursorModelAnimation" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.CursorModelAnimation \- CursorModelAnimation is used to animate the cursor model\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
CursorModelAnimation is used to animate the cursor model\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
