.TH "Player.PlayerBombController" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.PlayerBombController \- PlayerController is used to control the bombs of the player\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBPlayerInputHandler\fP playerInputHandler)"
.br
.RI "Initialize the player controller\&. "
.ti -1c
.RI "void \fBTryPlaceBomb\fP ()"
.br
.RI "Try to place a bomb\&. "
.ti -1c
.RI "void \fBOnBombExplode\fP ()"
.br
.RI "OnBombExplode is called when a bomb explodes\&. "
.ti -1c
.RI "void \fBAddBombPower\fP ()"
.br
.RI "Add bomb power\&. "
.ti -1c
.RI "void \fBRemoveBombPower\fP ()"
.br
.RI "Remove bomb power\&. "
.ti -1c
.RI "void \fBAddBombAmount\fP ()"
.br
.RI "Add bomb amount\&. "
.ti -1c
.RI "void \fBRemoveBombAmount\fP ()"
.br
.RI "Remove bomb amount\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBombPower\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PlayerController is used to control the bombs of the player\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Player\&.PlayerBombController\&.Initialize (\fBPlayerInputHandler\fP playerInputHandler)"

.PP
Initialize the player controller\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerInputHandler\fP The player input handler\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
