.TH "PlayerInputs.PlayerInputHandler" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerInputs.PlayerInputHandler \- PlayerInputHandler is used to handle the input of a player\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUsePlayerControls\fP ()"
.br
.RI "Use the player controls\&. "
.ti -1c
.RI "void \fBUseMenuControls\fP ()"
.br
.RI "Use the menu controls\&. "
.ti -1c
.RI "void \fBEnableInput\fP ()"
.br
.RI "Enable the input\&. "
.ti -1c
.RI "void \fBDisableInput\fP ()"
.br
.RI "Disable the input\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< Vector2, int > \fBOnDirection\fP"
.br
.ti -1c
.RI "Action< int > \fBOnConfirm\fP"
.br
.ti -1c
.RI "Action< int > \fBOnCancel\fP"
.br
.ti -1c
.RI "Action< Vector2 > \fBOnMove\fP"
.br
.ti -1c
.RI "Action \fBOnPlaceBomb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PlayerInputHandler is used to handle the input of a player\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
