.TH "PlyVoxelParseJob" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlyVoxelParseJob
.SH SYNOPSIS
.br
.PP
.PP
Inherits IJob\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecute\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NativeArray< char > \fBfileData\fP"
.br
.ti -1c
.RI "NativeArray< \fBJobVoxelData\fP > \fBvoxelData\fP"
.br
.ti -1c
.RI "NativeList< int > \fBvoxels\fP"
.br
.ti -1c
.RI "NativeList< int > \fBvoxelsShape\fP"
.br
.ti -1c
.RI "NativeList< int > \fBvoxelsCoordinates\fP"
.br
.ti -1c
.RI "NativeList< int > \fBvoxelsColors\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
