.TH "Terrain" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terrain
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerrainManager\fP"
.br
.RI "This class is used to manage the terrain\&. "
.ti -1c
.RI "class \fBTerrainUtils\fP"
.br
.RI "This class is used to get the position of the terrain\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTerrainEntityType\fP { \fBWall\fP, \fBIndestructibleEntity\fP, \fBBomb\fP, \fBNone\fP }"
.br
.RI "This enum is used to define the type of the terrain entity\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
