.TH "Utils.PlayerConfigurationDebugUtils" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils.PlayerConfigurationDebugUtils \- This class is used to print player configurations\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrintPlayerConfigurations\fP (List< \fBPlayerState\fP > playerConfigurations)"
.br
.RI "This method is used to print player configurations\&. "
.ti -1c
.RI "static string \fBFormatPlayerConfiguration\fP (\fBPlayerState\fP playerState)"
.br
.RI "This method is used to format a player configuration\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class is used to print player configurations\&. 
.SH "Member Function Documentation"
.PP 
.SS "static string Utils\&.PlayerConfigurationDebugUtils\&.FormatPlayerConfiguration (\fBPlayerState\fP playerState)\fC [static]\fP"

.PP
This method is used to format a player configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerState\fP The player configuration to format 
.RE
.PP
\fBReturns\fP
.RS 4
The formatted player configuration 
.RE
.PP

.SS "static void Utils\&.PlayerConfigurationDebugUtils\&.PrintPlayerConfigurations (List< \fBPlayerState\fP > playerConfigurations)\fC [static]\fP"

.PP
This method is used to print player configurations\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerConfigurations\fP The player configurations to print 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
