.TH "VoxelData" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoxelData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBVoxelDataReady\fP (\fBVoxelData\fP self)"
.br
.ti -1c
.RI "void \fBMarkReady\fP ()"
.br
.ti -1c
.RI "bool \fBIsReady\fP ()"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int[] \fBvoxels\fP"
.br
.ti -1c
.RI "int[] \fBvoxelsColors\fP"
.br
.ti -1c
.RI "int[] \fBvoxelsCoordinates\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "Vector3 \fBorigin\fP"
.br
.ti -1c
.RI "Vector3 \fBscale\fP"
.br
.ti -1c
.RI "bool \fBcanExplode\fP"
.br
.ti -1c
.RI "GraphicsBuffer \fBvoxelsColorBuffer\fP"
.br
.ti -1c
.RI "GraphicsBuffer \fBvoxelsCoordinateBuffer\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "VoxelDataReady \fBOnVoxelDataReady\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
