.TH "VoxelDataStore" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoxelDataStore
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVoxelData\fP \fBSetVoxelData\fP (string instanceID, \fBVoxelData\fP voxelData)"
.br
.ti -1c
.RI "\fBVoxelData\fP \fBGetVoxelData\fP (string instanceID)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBVoxelDataStore\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
