.TH "VoxelMeshStore" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoxelMeshStore
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVoxelMesh\fP \fBSetVoxelMesh\fP (string instanceID, \fBVoxelMesh\fP mesh)"
.br
.ti -1c
.RI "static \fBVoxelMesh\fP \fBGetVoxelMesh\fP (string instanceID)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
