.TH "VoxelGraph" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoxelGraph
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBAnimationEnd\fP ()"
.br
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVoxelParser\fP \fBvoxelParser\fP"
.br
.ti -1c
.RI "bool \fBautoDestroy\fP = true"
.br
.ti -1c
.RI "int \fBdestroyThreshold\fP = 100"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "AnimationEnd \fBOnAnimationEnd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
