.TH "VoxelParser" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoxelParser
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TextAsset \fBfile\fP"
.br
.ti -1c
.RI "\fBVoxelData\fP \fBvoxelData\fP"
.br
.ti -1c
.RI "JobHandle \fBparserJobHandle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
