.TH "VoxelMesh" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoxelMesh
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVoxelMesh\fP (int optimizationLevel=0)"
.br
.ti -1c
.RI "\fBVoxelMesh\fP (Mesh mesh, int optimizationLevel=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Mesh \fBmesh\fP"
.br
.ti -1c
.RI "int \fBoptimizationLevel\fP"
.br
.ti -1c
.RI "bool \fBwaitOptimization\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
