.TH "VoxelInfo" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoxelInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "short \fBz\fP"
.br
.ti -1c
.RI "byte \fBred\fP"
.br
.ti -1c
.RI "byte \fBgreen\fP"
.br
.ti -1c
.RI "byte \fBblue\fP"
.br
.ti -1c
.RI "byte \fBalpha\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
