.TH "Wall" 3 "Sun Apr 9 2023" "Alkemy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Wall
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDestructibleWall\fP"
.br
.RI "This class is used to manage the destructible wall\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alkemy from the source code\&.
